exports.obj =[
    {label: 'true',kind: 13,detail: "keyword"},
    {label: 'false',kind: 13,detail: "keyword"},
    {label: 'left',kind: 13,detail: "keyword"},
    {label: 'right',kind: 13,detail: "keyword"},
    {label: 'centered',kind: 13,detail: "keyword"},
    {label: 'top',kind: 13,detail: "keyword"},
    {label: 'bottom',kind: 13,detail: "keyword"},
    {label: 'dialog_line',kind: 13,detail: "keyword"},
    {label: 'dialog_foreground',kind: 13,detail: "keyword"},
    {label: 'dialog_background',kind: 13,detail: "keyword"},
    {label: 'graphics_background',kind: 13,detail: "keyword"},
    {label: 'black',kind: 13,detail: "keyword"},
    {label: 'red',kind: 13,detail: "keyword"},
    {label: 'yellow',kind: 13,detail: "keyword"},
    {label: 'green',kind: 13,detail: "keyword"},
    {label: 'cyan',kind: 13,detail: "keyword"},
    {label: 'blue',kind: 13,detail: "keyword"},
    {label: 'magenta',kind: 13,detail: "keyword"},
    {label: 'white',kind: 13,detail: "keyword"},
    {label: 'graphics_foreground',kind: 13,detail: "keyword"},
    {label: 'horizontal',kind: 13,detail: "keyword"},
    {label: 'vertical',kind: 13,detail: "keyword"},
]