exports.obj = [
    {label: 'boxed_column',kind: 21,detail: "tile"},
    {label: 'boxed_radio_column',kind: 21,detail: "tile"},
    {label: 'boxed_radio_row',kind: 21,detail: "tile"},
    {label: 'boxed_row',kind: 21,detail: "tile"},
    {label: 'button',kind: 21,detail: "tile"},
    {label: 'column',kind: 21,detail: "tile"},
    {label: 'concatenation',kind: 21,detail: "tile"},
    {label: 'dialog',kind: 21,detail: "tile"},
    {label: 'edit_box',kind: 21,detail: "tile"},
    {label: 'errtile',kind: 21,detail: "tile"},
    {label: 'image',kind: 21,detail: "tile"},
    {label: 'image_button',kind: 21,detail: "tile"},
    {label: 'list_box',kind: 21,detail: "tile"},
    {label: 'ok_cancel',kind: 21,detail: "tile"},
    {label: 'ok_cancel_help',kind: 21,detail: "tile"},
    {label: 'ok_cancel_help_errtile',kind: 21,detail: "tile"},
    {label: 'ok_cancel_help_info',kind: 21,detail: "tile"},
    {label: 'ok_only',kind: 21,detail: "tile"},
    {label: 'paragraph',kind: 21,detail: "tile"},
    {label: 'popup_list',kind: 21,detail: "tile"},
    {label: 'radio_button',kind: 21,detail: "tile"},
    {label: 'radio_column',kind: 21,detail: "tile"},
    {label: 'radio_row',kind: 21,detail: "tile"},
    {label: 'row',kind: 21,detail: "tile"},
    {label: 'slider',kind: 21,detail: "tile"},
    {label: 'spacer',kind: 21,detail: "tile"},
    {label: 'spacer_0 ',kind: 21,detail: "tile"},
    {label: 'spacer_1 ',kind: 21,detail: "tile"},
    {label: 'text',kind: 21,detail: "tile"},
    {label: 'toggle',kind: 21,detail: "tile"},
]